version: '3'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.pub
    image: backend-release:1.0.2
    #image: waysamurai/kupipodariday-backend:1.0.2
    env_file: .env
    environment:
      - npm_config_audit=false
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    restart: always
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.pub
    image: frontend-release:1.0.2
    #image:  waysamurai/kupipodariday-frontend:1.0.2
    env_file: .env
    environment:
      - npm_config_audit=false
    ports:
      - '8081:80'
    restart: always
    networks:
      - frontend
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  postgres_data:
networks:
  backend:
  frontend:
