version: '3'

services:
  backend:
    container_name: 'backend'
    image: waysamurai/kupipodariday-backend:1.0.0
    env_file: .env
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    networks: 
      - backend

  frontend:
    container_name: 'frontend'
    image:  waysamurai/kupipodariday-frontend:1.0.0
    env_file: .env
    ports:
      - '8081:80'
    restart: always
    networks:
      - frontend

  postgres:
    container_name: 'kupipodariday-database'
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - postgres  
    networks: 
      - backend

volumes: 
  postgres_data: 

networks:
  backend:
  frontend: