version: '3'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    image: backend
    env_file: .env
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    restart: always
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
    networks:
      - backend
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: frontend
    env_file: .env
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '3001:3000'
    restart: always
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    networks:
      - frontend
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  postgres_data:
networks:
  backend:
  frontend: