version: '3'

services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    restart: always
    env_file: .env
    environment:
      CHOKIDAR-USEPOOLING: 'true'
    ports:
      - '3001:80'
    networks:
      - frontend

  postgres:
    container_name: 'kupipodariday-database'
    image: postgres:12.12-alpine
    restart: always
    env_file: .env
    volumes:
      - ~/pg_data:/var/lib/postgresql/data

    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:
