FROM node:16.15-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . ./
RUN npm run build \
    rm -rf ./src \
    rm -rf node ./node_modules

FROM node:16.15-alpine AS backend
WORKDIR /app
COPY package*.json ./
RUN npm i --omit=dev --no-audit --no-fond && npm install -g pm2
COPY --from=builder /app/dist ./dist
COPY ./ecosystem.config.js ./
EXPOSE 3000

CMD ["pm2-runtime", "start", "ecosystem.config.js"]